apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc		 # volume name
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi		
  storageClassName: gp2	# type(gp3/standard)

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb
    spec:
      securityContext:
        fsGroup: 1001		      # assign ID to volume (mt pods)
      containers:
      - name: mariadb
        image: bitnami/mariadb:latest

        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_USER
          value: "bn_moodle"
        - name: MARIADB_PASSWORD
          value: "bitnami"
        - name: MARIADB_DATABASE
          value: "bitnami_moodle"
        - name: MOODLE_DATABASE_HOST		 
          value: "mariadb.default.svc.cluster.local"	
#docker have nt, eks need create service(port+target) in cluster for local cmu
#container:
        securityContext:
          runAsUser: 1001      # assign user ID to containers

        volumeMounts:          # mount volume
        - mountPath: /bitnami/mariadb
          name: mariadb-data
#spec:
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: default
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306		    # expose
    targetPort: 3306  # CT listener
