apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle

  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: bitnami/moodle:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https

        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MOODLE_DATABASE_USER
          value: "bn_moodle"			    # root
        - name: MOODLE_DATABASE_PASSWORD
          value: "bitnami"		        # 12345678
        - name: MOODLE_DATABASE_NAME
          value: "bitnami_moodle"
        - name: MOODLE_DATABASE_HOST  # cmu with mariadb pod / Aura_EP
          value: "mariadb.default.svc.cluster.local"
#container:
        volumeMounts:
        - mountPath: /bitnami/moodle
          name: moodle-data
#spec:
      volumes:
      - name: moodle-data
        persistentVolumeClaim:
          claimName: moodle-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: default
spec:
  selector:
    app: moodle

  ports:
  - protocol: TCP
    port: 80			    # income 80
    targetPort: 8080  # forward to pod 8080
    name: http

  - protocol: TCP	    # income 443
    port: 443         # income 8443
    targetPort: 8443
    name: https
  type: LoadBalancer
