apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app-v2
  labels:
    app: two-tier-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app
      version: v2
  template:
    metadata:
      labels:
        app: two-tier-app
        version: v2
    spec:
      containers:
      - name: two-tier-app
        image: trainwithshubham/flaskapp:latest
        envFrom:
          - configMapRef:
              name: flask-config
        env:
          - name: MYSQL_HOST
            value: "database-1.cluster-cp9hsrnhtomo.us-east-1.rds.amazonaws.com"
          - name: MYSQL_PASSWORD
            value: "12345678"
        ports:
          - containerPort: 5000
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: two-tier-app-service
spec:
  selector:
    app: two-tier-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP